services:
  - type: web
    name: shopping-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_DEFAULT_REGION
        value: us-east-1
      - key: S3_BUCKET_NAME
        value: ecommersfashion-images-bucket
      - key: RDS_HOST
        sync: false
      - key: RDS_USER
        sync: false
      - key: RDS_PASSWORD
        sync: false
      - key: RDS_DB
        value: SQLRDSAWS
